brightness: 100
auto_reload: true
long_press_duration: 0.5
pages:
  - name: Home
    buttons: !include includes/home.yaml
  - name: Living Room
    buttons: !include includes/room_living_room.yaml
  - name: Bedroom
    buttons: !include includes/room_bedroom.yaml
  - name: Kitchen
    buttons: !include includes/room_kitchen.yaml
